"""Google-federated identity with rotating refresh tokens.

Access tokens are short-lived signed JWTs the API dependency verifies on every
request. Refresh tokens are opaque random strings; only their SHA-256 hash is
persisted. Each refresh rotates the token within its family, and presenting an
already-revoked token revokes the entire family (reuse detection).
"""
from __future__ import annotations

import hashlib
import secrets
import uuid
from datetime import datetime, timedelta, timezone

from fastapi import HTTPException, status
from google.auth.transport import requests as google_requests
from google.oauth2 import id_token as google_id_token
from jose import JWTError, jwt
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from api.config import settings
from api.models import RefreshToken, UsageAccount, User


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _as_aware(value: datetime) -> datetime:
    """SQLite returns tz-naive datetimes; treat stored values as UTC."""
    return value if value.tzinfo is not None else value.replace(tzinfo=timezone.utc)


def _require_configured() -> tuple[str, str]:
    if not settings.jwt_secret:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="authentication is not configured; set SINGULARITY_JWT_SECRET",
        )
    if not settings.google_client_id:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="authentication is not configured; set SINGULARITY_GOOGLE_CLIENT_ID",
        )
    return settings.jwt_secret, settings.google_client_id


def create_access_token(user_id: str) -> tuple[str, int]:
    """Return a signed access JWT and its lifetime in seconds."""
    secret = settings.jwt_secret
    if not secret:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="authentication is not configured; set SINGULARITY_JWT_SECRET",
        )
    ttl = settings.access_token_ttl_seconds
    now = _now()
    payload = {
        "sub": user_id,
        "iat": int(now.timestamp()),
        "exp": int((now + timedelta(seconds=ttl)).timestamp()),
        "type": "access",
    }
    return jwt.encode(payload, secret, algorithm=settings.jwt_algorithm), ttl


def decode_access_token(token: str) -> str:
    """Return the subject user id, or raise 401 for any invalid access token."""
    secret = settings.jwt_secret
    if not secret:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="authentication is not configured; set SINGULARITY_JWT_SECRET",
        )
    try:
        payload = jwt.decode(token, secret, algorithms=[settings.jwt_algorithm])
    except JWTError as exc:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid or expired token") from exc
    if payload.get("type") != "access" or not payload.get("sub"):
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid token")
    return str(payload["sub"])


def _hash_refresh_token(raw: str) -> str:
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


async def _issue_refresh_token(session: AsyncSession, user_id: str, family_id: str) -> str:
    raw = secrets.token_urlsafe(48)
    session.add(
        RefreshToken(
            user_id=user_id,
            token_hash=_hash_refresh_token(raw),
            family_id=family_id,
            expires_at=_now() + timedelta(seconds=settings.refresh_token_ttl_seconds),
        )
    )
    return raw


async def _ensure_usage_account(session: AsyncSession, user: User) -> None:
    existing = await session.scalar(select(UsageAccount).where(UsageAccount.user_id == user.id))
    if existing is None:
        session.add(UsageAccount(user_id=user.id))


async def _issue_session(session: AsyncSession, user: User) -> tuple[User, str, str, int]:
    """Issue and persist one access/refresh pair for an active user."""
    if user.status != "active":
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="User is not active")
    await _ensure_usage_account(session, user)
    family_id = str(uuid.uuid4())
    access_token, expires_in = create_access_token(user.id)
    refresh_token = await _issue_refresh_token(session, user.id, family_id)
    await session.commit()
    await session.refresh(user)
    return user, access_token, refresh_token, expires_in


async def cli_device_login(session: AsyncSession, raw_device_token: str) -> tuple[User, str, str, int]:
    """Upsert an anonymous CLI identity derived from a local high-entropy token.

    The raw device token is never persisted. It is generated by the CLI on its
    first API call and kept in the same private settings file as the BYOK key.
    This gives a shipped CLI a normal bearer-authenticated API session without
    requiring Google login or asking the user to configure an application env.
    """
    if not settings.jwt_secret:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="authentication is not configured; set SINGULARITY_JWT_SECRET",
        )
    subject = hashlib.sha256(raw_device_token.encode("utf-8")).hexdigest()
    result = await session.execute(
        select(User).where(User.auth_provider == "cli_device", User.external_subject == subject)
    )
    user = result.scalar_one_or_none()
    if user is None:
        user = User(
            auth_provider="cli_device",
            external_subject=subject,
            display_name="Singularity CLI",
            status="active",
        )
        session.add(user)
        await session.flush()
    return await _issue_session(session, user)


async def google_login(session: AsyncSession, raw_id_token: str) -> tuple[User, str, str, int]:
    """Verify a Google id_token, upsert the user, and mint a fresh token pair."""
    _, client_id = _require_configured()
    try:
        claims = google_id_token.verify_oauth2_token(
            raw_id_token, google_requests.Request(), client_id
        )
    except ValueError as exc:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid Google id_token") from exc

    subject = claims.get("sub")
    if not subject:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Google id_token missing subject")

    result = await session.execute(
        select(User).where(User.auth_provider == "google", User.external_subject == subject)
    )
    user = result.scalar_one_or_none()
    if user is None:
        user = User(
            auth_provider="google",
            external_subject=subject,
            email=claims.get("email"),
            display_name=claims.get("name") or claims.get("email"),
            status="active",
        )
        session.add(user)
        await session.flush()
        await _ensure_usage_account(session, user)
    else:
        if user.status != "active":
            raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="User is not active")
        if claims.get("email"):
            user.email = claims["email"]
        if claims.get("name"):
            user.display_name = claims["name"]
        await _ensure_usage_account(session, user)

    return await _issue_session(session, user)


async def refresh(session: AsyncSession, raw_refresh_token: str) -> tuple[str, str, int]:
    """Rotate a refresh token, detecting and revoking reused token families."""
    token_hash = _hash_refresh_token(raw_refresh_token)
    result = await session.execute(select(RefreshToken).where(RefreshToken.token_hash == token_hash))
    stored = result.scalar_one_or_none()
    if stored is None:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid refresh token")

    if stored.revoked_at is not None:
        # Reuse of a rotated token: revoke the whole family so a leaked token
        # cannot be used to fork a parallel valid session.
        await _revoke_family(session, stored.family_id, reason="reuse_detected")
        await session.commit()
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Refresh token reuse detected")

    if _as_aware(stored.expires_at) <= _now():
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Refresh token expired")

    stored.revoked_at = _now()
    stored.revoked_reason = "rotated"
    stored.last_used_at = _now()
    access_token, expires_in = create_access_token(stored.user_id)
    new_refresh = await _issue_refresh_token(session, stored.user_id, stored.family_id)
    await session.commit()
    return access_token, new_refresh, expires_in


async def logout(session: AsyncSession, raw_refresh_token: str) -> None:
    """Revoke the presented refresh token and its family (idempotent)."""
    token_hash = _hash_refresh_token(raw_refresh_token)
    result = await session.execute(select(RefreshToken).where(RefreshToken.token_hash == token_hash))
    stored = result.scalar_one_or_none()
    if stored is None:
        return
    await _revoke_family(session, stored.family_id, reason="logout")
    await session.commit()


async def _revoke_family(session: AsyncSession, family_id: str, *, reason: str) -> None:
    result = await session.execute(
        select(RefreshToken).where(RefreshToken.family_id == family_id, RefreshToken.revoked_at.is_(None))
    )
    for token in result.scalars():
        token.revoked_at = _now()
        token.revoked_reason = reason
